### ISSUE TITLE
Crashed Error

### ISSUE THREAD

**Issue by jokerkeny** [Stickymaddness/Procurement#1122]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/5362983/DebugInfo.log)

The program crashed when I search "stone" in my stash, which are included in 2 stash tabs.

**Comment by thailyn** [comment]
I think this is the same issue as #1117.  I made a fix for that that is linked [here](https://github.com/Stickymaddness/Procurement/issues/1117#issuecomment-698026185).  Please see if the issue is resolved there.  If not, please attach your `.bin` files, as I can't recreate the issue with my own stash tabs.
