### ISSUE TITLE
Procurement not interacting with forums

### ISSUE THREAD

**Issue by Nolorwolf** [Stickymaddness/Procurement#118]
Some time in last 48h program stopped interacting with forum for a lot of people. Idk anyone for whom it works, but I didn't ask a lot. It gives false messages that the thread is updated/bumped, while it's actually not, so I guess a lot of people won't notice it soon.

A lot of people did notice that their b/o prices disappeared, which might be related.

**Comment by roborobp** [comment]
I am also having this same issue. Uninstalled and reinstalled and even tried a new shop thread.

**Comment by BanditBanditBandit** [comment]
I am also having this same issue. Its telling me that its updating fine and dandy, but if I look at my thread it does not update it at all. I have seen elsewhere that this software is no longer being supported because the developer has stated that he no longer plays POE. I hope this can be resolved, or maybe even adding in the auto updating things that Acquisition offers. (the formating for the forum post it gives you is just.... horrible... I would rather stick with this program)

**Comment by Stickymaddness** [comment]
Procurement 1.9.3 has been released, which fixes this issue! 

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.3
