### ISSUE TITLE
[Feature Request] Time since last bump

### ISSUE THREAD

**Issue by Potawto** [Stickymaddness/Procurement#137]
Just a small idea, a timer (perhaps on the Trading or Trading->Forum Export tab) showing the amount of time since the latest bump.

**Comment by medvedttn** [comment]
There are 2 options as I see:
1) count time since last button "Bump" click.Simple timer, but on program exit counter will be reset to 0.
2) parse forum thread and analyze last post (post time) in some time period (for example, 5min).Can correct handle user manual bumps/messages in thread.

3) Using alarm clock  :)

**Comment by Potawto** [comment]
I use Orzeszek Timer, personally. 

I don't think it has to be complicated, time since last button push with no attempt at persistence would still be convenient.

Hardly important, either way.

**Comment by Stickymaddness** [comment]
I'll give this some thought and see what I can do in the next release.

**Comment by Stickymaddness** [comment]
I'm going to close this for now, but will keep it in mind. GGG have hinted at API improvements coming "soon" which is going to streamline how items are posted and shops updated. I want to see what their changes are going to be before looking at item posting / bumping further.
