### ISSUE TITLE
Individual prices not sticking.

### ISSUE THREAD

**Issue by Nhatorama** [Stickymaddness/Procurement#140]
I have a lot of white onyx amulets with different ilvl that I want to price differently. They all have the same implicit value.
If I price an onyx amulet a certain value, once I go to the trading tab all other onyx amulet prices are changed to the first onyx amulet b/o price.

**Comment by Stickymaddness** [comment]
Unfortunately ilvl is not returned by the GGG API, we have been asking them for years to include it.

Due to the way the current Procurement code works it will not differentiate between the same white items as you've seen. While it would technically be possible to change this, it would cause all gear buyouts of all users to be lost as it would change the unique id of all gear items.

**Comment by Nhatorama** [comment]
Hi, thanks for answering.

Do you have a link where I can vote my support for including ilvl to be returned by the API

**Comment by Stickymaddness** [comment]
Not really no. Someone had a thread up at some point, it might have even been xyz I can't remember, but it didn't really go anywhere unfortunately.
