### ISSUE TITLE
[Error] Error reading character data 

### ISSUE THREAD

**Issue by ekoar** [Stickymaddness/Procurement#169]
I am receiving the error "[Error] Error reading character data for teaaa, if you are in offline mode you will need to login and update. Make sure that your account name is entered correctly and with the correct casing. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again."

I have read other remarks regarding this issue and understand this may happen when entering characters wrong as it is case sensitive. Problem is, this is not happening to my "login" character. This is happening to another character i have on the same league. I have tried deleting the character which creates the problem and procurement just goes to the next character and has the same issue.

To be clear, I log in to procurement and it loads my stash tabs, It than tries loading all other characters inventory which is when the error occurs.

**Comment by moustaffa** [comment]
I am having this exact problem as well.  Sometimes it will say what he is getting, and sometimes it will simply have an error of "Error: Failed to load characters".  I have DEFINITELY spelled my character name right and it's not loading ANY characters, not just the one I typed in under Account Name.  I haven't used Procurement since 1.8.6, but it definitely worked then.  

I uninstalled and re-installed (Using 1.9.2, as that was the newest installer on the site?) then copied and pasted the 1.9.5 version into the installer folder.  PLEASE HELP!
![procurement error](https://cloud.githubusercontent.com/assets/13972085/9482443/5cdf463e-4b62-11e5-8287-1518ef8d0192.png)

**Comment by ekoar** [comment]
I had this issue as well, My "Account Name" i was using was misspelled.If you go to path of exile forums and log in, in the top left corner above the "log out" and "messages" tabs, it will state "Logged in as XXXX". This XXXX is the account name needed for Procurement. Your account name is a name you chose when creating your path of exile account and is totally different to your character names. Hope this helps.
