### ISSUE TITLE
Error reading character data.

### ISSUE THREAD

**Issue by driz** [Stickymaddness/Procurement#178]
I updated procurement and can no longer login with it. I'm a steam player so I typically use my session ID. this part is working fine, i can see if load all my stash tabs. When it gets to one of my characters, it fails. I've logged in as the character, i've switched to it on the forums, nothing helps. I can't get beyond this step.

Here's the info from the Debug (and screenshot below)

[21-08-2015 14:45] Error reading character data for character 'Ariellan', Exception info: 
[21-08-2015 14:45] System.Exception: Error reading character data for Ariellan, if you are in offline mode you will need to login and update. Make sure that your account name is entered correctly and with the correct casing. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

![image](https://cloud.githubusercontent.com/assets/364867/9417632/91277bfc-4813-11e5-8bce-c414e537abf1.png)

**Comment by driz** [comment]
I also tried removing the whole folder and starting clean, exact same error.

**Comment by Stickymaddness** [comment]
It looks like you've been doing everything correctly, and since there have been no character related changes in the last version of Procurement I can only assume the GGG api is no longer returning your character data, for whatever reason.

If you open settings.xml and set DownloadOnlyMyCharacters to true with no characters in the MyCharacters section it will skip downloading your characters and you should be able to login.

If you login to the forum, try to download the data for one of your characters manually by going to the url

    https://www.pathofexile.com/character-window/get-items?character=YOURCHARACTERHERE&accountName=Ariellan

Replace YOURCHARACTERHERE with the name of one of your characters. It should display a giant block of json with all the data for your character.

**Comment by JherNifol** [comment]
Same issue here, http://www.pathofexile.com/character-window/get-items?character={0}&accountName={1} returns "false" (substituting brackets etc) 

I attempted logging in/out from the PoE website, checked my settings on my profile so that nothing was hidden or anything, cleared cache, still returning "false" on "get-items"

"https://www.pathofexile.com/character-window/get-characters" Working fine however

Not an issue with procurement, though I don't know much about why this might be happening on GGG's end

Do you know if this is a very widespread issue?

**Comment by Stickymaddness** [comment]
@JherNifol are you 100% certain your account name was correct? If so, interesting.

Yes, this seems to be a very widespread issue, I have countless reports of users with this error. I will have to build in some fault tolerance for this, and make Procurement skip characters that return invalid data.

**Comment by JherNifol** [comment]
Oh wow, that's embarrassing, my account name was in fact, incorrect
(Having made the account quite a while ago, I seemed to have used a shortened version of my usual username that I typically just use as a character name in games so I didn't spot it right away on the site as being different from just another one of my characters)

get-items working correctly now

Perhaps that's part of the issue others are having then?
To log into the PoE site they use your email for login, not requiring the account name, so when people attempt to log into Procurement by inputting both, they simply aren't remembering their account name correctly, or just default to their email, sans the @

**Comment by driz** [comment]
ok, i had the same issue. My account name was wrong. What's interesting is i initially used the same settings.xml from 1.9.4 when i upgraded. As a steam user, i had no clue what credentials to use, so i just used session id, i was under the impression it would utilize the proper account name. It's corrected now, i apologize for the inconvenience! thanks for your assistance!
