### ISSUE TITLE
Debug.Log Error

### ISSUE THREAD

**Issue by xosernest** [Stickymaddness/Procurement#222]
Hi i saw that the way to fix it was to sell all the maps, does it mean we can't hold any maps at all in our stash? 

Will this issue be fixed or will it stay like this ?

Hope to get a understanding on this issue.

**Comment by Stickymaddness** [comment]
The problem was the map tier change which broke Procurement.

The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6 with the new version you can keep all your maps as usual.

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
