### ISSUE TITLE
6L rare chest listed as dagger

### ISSUE THREAD

**Issue by IceLancerSR** [Stickymaddness/Procurement#281]
Hello, i find this bug bit funny and annoying.
For some reason my 6L hybrid chest keep getting listed as dagger.
I have not changed anything in forum template except that i removed gems for being listed.

https://www.pathofexile.com/forum/view-thread/1244061/page/1

Here is store page.
As you can see Vortex Coat keep ending up in daggers section..

Weapons and armor ->daggers.
It should be listed under Chest armor long with other 6L rare chest.

**Comment by Stickymaddness** [comment]
Hah, it's been a while since I've had one of these bugs.

I'll sort it out asap along with the release which will fix the broken login.

**Comment by Stickymaddness** [comment]
I didn't manage to get a fix for this out with 1.9.7, can you send me your .bin files so I can load up your items and test.

**Comment by IceLancerSR** [comment]
http://www92.zippyshare.com/v/xsgY0Iqf/file.html
here they are

**Comment by trackpete** [comment]
I recently had the same problem with the ExileTools Indexer, if you haven't isolated this it's almost certainly the same problem I had with my base item type lookup. The `Sai` dagger type is getting matched before `Saintly Chainmail` - I fixed it in my tool by changing the comparison to do whole word matching instead of "is in" matching.

**Comment by Stickymaddness** [comment]
I'm sorry this old issue never got any proper attention, but I do think it was fixed back when the item matching code was overhauled.
