### ISSUE TITLE
Certain items wont get templated?

### ISSUE THREAD

**Issue by NiksBrotha** [Stickymaddness/Procurement#435]
I am not sure but some of my items don't show up in the forum template when I try to update and then bump. For instance, my "Enlightened" divination card doesn't show up and a few other things even though I have a buyout listed for them. I have tried moving them around in my stash and other things but no fix so far.

Bumping is also an issue at times.I have the 1.9.8-rc1 version
[DebugInfo.zip](https://github.com/Stickymaddness/Procurement/files/93216/DebugInfo.zip)

**Comment by NiksBrotha** [comment]
Any suggestions? Help? Half of my items aren't getting formatted in the "Forum Export" section after I have updated my prices and even without prices they don't get templated.

**Comment by Stickymaddness** [comment]
Hi,

Divination cards not being generated is probably due to them being newer and missing from the data.xml file (https://github.com/Stickymaddness/Procurement/blob/master/POEApi.Model/Data.xml) if you open the file and go to the bottom you'll see a section for divination cards, add the missing cards there are restart Procurement, and the missing cards should now generate properly.

**Comment by Stickymaddness** [comment]
Procurement 1.9.9 has been released, which includes all the missing cards:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9
