### ISSUE TITLE
Error when loading perandus stashes

### ISSUE THREAD

**Issue by Falkan432** [Stickymaddness/Procurement#497]
i get an error when trying to load my perandus stash. this is the debug info:

[05-03-2016 1:39] ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
[05-03-2016 1:39] System.Exception: ProxyMapper.GetOrbType Failed! ItemType = Perandus Coin
   ved POEApi.Model.ProxyMapper.GetOrbType(String name)
   ved POEApi.Model.Currency..ctor(Item item)
   ved POEApi.Model.ItemFactory.Get(Item item)

**Comment by Stickymaddness** [comment]
This is due to the Perandus Coins in your stash, Procurement unfortunately does not currently have support for this item. I will add support in the next release but it may be some time before that is released.

**Comment by Falkan432** [comment]
dont want to be pushy, but do you know how much time? are we talking days or weeks? I want to start trading in the Perandus league, and wanted to use procurement for that. Thanks for your answer.

**Comment by Stickymaddness** [comment]
Nothing wrong with asking for a timeline. At this stage it's more likely to be weeks.

While not ideal, the best you can do until then if you want to use Procurement is to put your perandus coins in a separate tab and not download that tab with Procurement.

**Comment by Falkan432** [comment]
ok, might do that, im looking at acqusition right now, and i deffinetly prefer Procurement. Thanks for all your help

**Comment by Falkan432** [comment]
Hey i am unsure how to write in the tabs i want to load, could you just give me a quick example?


      </List>

im not sure where i should write, and how.

**Comment by Stickymaddness** [comment]
Sure,

For example, lets say you only wanted three tabs to be download, Shop1, Shop2 and Other. 

Your settings file should look like this:

```xml
    <List name="MyTabs">
      <!--If you only want Procurement to download specific tabs list them here, eg :-->
        <Item value="Shop1" />
        <Item value="Shop2" />
        <Item value="Other" />
    </List>
```

Note that I removed the  from each line for our tabs, since that creates a "comment" and disables that line from being loaded.

**Important:** Due to the way the GGG api works, your first tab is _always_ downloaded, no matter what your settings are. Many players, myself included, use the first tab for currency and if you are too you would need to put your coins in a different tab.

**Comment by Falkan432** [comment]
cool, hot it to work, thanks again

**Comment by Stickymaddness** [comment]
Glad you got it sorted.
