### ISSUE TITLE
Cannot log in procurment

### ISSUE THREAD

**Issue by Lina5555** [Stickymaddness/Procurement#575]
[DebugInfo.txt](https://github.com/Stickymaddness/Procurement/files/200793/DebugInfo.txt)

**Comment by Stickymaddness** [comment]
Procurement 1.9.9 has been released, please retest and reopen your issue if your error persists:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9

**Comment by tanvirulislam427** [comment]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2660830/DebugInfo.log)

**Comment by thailyn** [comment]
Hi, @tanvirulislam427, thanks for the report.  In the future, please open a new issue instead of updating a closed one if it is not directly related.

The server is giving a 404 error (page not found) when trying to fetch your initial hardcore league stash tab.  This might be a transient error on GGG's part, but we could use more information.  Is this your first time using Procurement?  Has it been able to download that tab before?  Do you have any characters in the hardcore league?

If you do not need that league's stash tabs, you can disable fetching them.  Uncheck "Refresh on Login" on the login page, then go to the settings tab, enable "Download Only Selected Leagues", and uncheck the Hardcore league.
