### ISSUE TITLE
Not refreshing online status

### ISSUE THREAD

**Issue by rigoparis** [Stickymaddness/Procurement#626]
Hello, I tried replying to a post that specified this same issue, but didn't get an answer

Basically I can't get procurement to keep my online status automatically, it DOES refresh once, but after that it doesn't refresh anymore, been doing tests and trying stuff for two days, still doesn't work.

Would you mind looking into this?

Many thanks for the app and for your time!

**Comment by simppak** [comment]
I'm quite sure this issue was introduced in 688ae0aaa39c74e1efa6a14a43287b5dec86c387
At line 60 there is a fixed value of 55 minutes to change a boolean value, which in turn is used at line 86 to trigger a refresh.

There is a separate 2 minute timer created in the constructor to trigger an event to call RefreshOnlineStatus, but since there is a separate 55 minute check, it doesn't work.

**Comment by CritPower** [comment]
Need to change from 55 to 5.
                if (timeSinceLastOnline.Minutes > 55)
                {
                    currentlyOnline = false;
                }

**Comment by Stickymaddness** [comment]
This has been fixed thanks to [the PR](https://github.com/Stickymaddness/Procurement/pull/629) from @CritPower 

New release by the end of the week

**Comment by simppak** [comment]
Uh no. The issue is only half fixed.

Now you have a 2 minute timer calling a function, which keeps checking if 5 minutes has passed.
Why would you have two time checks? This also leads to a gap where the user will be marked as as offline for 1 minute.
0 min - 1st call: 5 minutes passed -> online triggered
2 min - 2nd call: 5 minutes has not passed
4 min - 3rd call: 5 minutes has not passed
(5 min - user marked as offline by poe.trade)
6 min - 4th call: 5 minutes passed -> online triggered

**Comment by Stickymaddness** [comment]
I'll take a closer look when I have time to work on the new release, the necessity of Procurement tracking user inactivity is now debatable since poe.trade expires online status so quickly.

@simppak you're welcome to submit a PR.

**Comment by simppak** [comment]
I only have a limited experience with C#, so I hesitate to make a rewrite. Thought I'd point out confusing programming logic. Thank you for maintaining Procurement though :)
