### ISSUE TITLE
Download again and again

### ISSUE THREAD

**Issue by TirMcDohl** [Stickymaddness/Procurement#710]
I've downloaded the latest Procurement 1.14.0 and when im launch it a message appear that saying the i have to update to newest version. I did it 3 times and it still the same. What to do?

**Comment by Kryptique** [comment]
Getting the same thing. The main window says it`s 1.14.0 but the procurement.exe version is still at 1.12.0 so that`s probably why it keeps triggering at every startup.

![procurement version issue](https://user-images.githubusercontent.com/30754249/28996906-26699c80-79d7-11e7-8e1e-d79057c07a2f.JPG)

**Comment by TirMcDohl** [comment]
so it can be fixed or will  be?

**Comment by aydjay** [comment]
I will investigate this issue tomorrow.

Something has gone wrong with the deployment. Thanks for the patience.

**Comment by Stickymaddness** [comment]
This is my fault, sorry about the annoyance.

As @Kryptique noted the assembly versions are still set to 1.12.0 despite it being the 1.14.0 release.

@aydjay  The version checker should be updated to use the version from [ApplicationState.cs ](https://github.com/Stickymaddness/Procurement/blob/master/Procurement/Utility/VersionChecker.cs#L47), which will allow bumping of the version in ApplicationState after appveyor has deployed a new version.
