### ISSUE TITLE
Procurement Log In Error

### ISSUE THREAD

**Issue by egerpad** [Stickymaddness/Procurement#889]
As it seems i cannot use the Procurement since yesterday...

[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2441162/DebugInfo.log)

**Comment by egerpad** [comment]
Hallo ?!

**Comment by thailyn** [comment]
It's hard to tell exactly what's going wrong in this case because, unfortunately, Procurement isn't logging a lot of information.  It's getting a 404 error when trying to fetch one of your stash tabs in standard.  Are you getting this error for the same tab every time, or is it different tabs?  Were you able to download your standard tabs before?

Also, if you don't need to download the standard league tabs, you can modify the `Settings.xml` file to set `DownloadOnlyMyLeagues` to `True` to download only your selected leagues, and include only the leagues you want in the `MyLeagues` list.
