### ISSUE TITLE
Stickymaddness missing?

### ISSUE THREAD

**Issue by EspadaSer** [Stickymaddness/Procurement#892]
Well it seems that Stickymaddness dissapeared and the pull requests are not attended. I have some issuses with forum thread not updating and messages not indicating item position that are solved, they just need to push the update. What can we do? It's very sad to let this great tool die.

**Comment by aydjay** [comment]
Probably didn't want to have to digest #877  PR 😆

**Comment by thailyn** [comment]
It's an open source project, so there are plenty of things we *can* do, if it comes down to it. I had considered, for example, making up a release from my local fork for the time being and telling people they could use that, but since the issues in the program right now can be worked around (e.g., copying the forum text from Procurement and updating the forum manually), I didn't think it was worth the additional complications and confusion to the user.

Moreover, this is just a hobby for us all. Stuff cones up. Stickymaddness is allowed to take a break if he wants (I know I've spent months, if not years, away from PoE and Procurement at times, and recently).

We're already half-way through the current league, so I don't really see a rush to release anything right now. We've got PR's for the biggest bugs with some additional infrastructure to help investigate other issues, and I can whip up some more PRs once these are accepted, so that puts us in a good spot.

On the eve of the next league in December, which is supposed to be a big update, it'll be another story. :)

**Comment by Stickymaddness** [comment]
As thailyn alluded to, I'm not actively maintaining Procurement anymore and haven't made a code change in ages. I do however need to be better at merging the great work @aydjay and @thailyn (and others) have been doing, so I'll make a point of merging PRs asap.

Consider me reminded @EspadaSer ;)
