### ISSUE TITLE
Error reading character data.

### ISSUE THREAD

**Issue by monosko** [Stickymaddness/Procurement#92]
[Error] Error reading character data for Vietra, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

What do?

![image](https://cloud.githubusercontent.com/assets/12062118/7267823/3240d2b6-e88f-11e4-9569-152826d4c827.png)

**Comment by Adylucas** [comment]
Same problem as you!

**Comment by comamitc** [comment]
OK so I think I figured out the issue.  The URL that is being currently used to get items for a character is wrong / has been changed by GGG.

You now need the` accountName` parameter as well in the request. I tested this out in postman and without the accountName parameter there is an empty but 200 OK reponse.  I won't bother making a pull request since I don't have C#.

http://www.pathofexile.com/character-window/get-items?character=Rustilia&accountName=comamitc

cc: @Stickymaddness

**Comment by comamitc** [comment]
Just letting everyone know a fix has been provided here: https://github.com/medvedttn/Procurement/releases/tag/1.9.1

**Comment by CosmicLight** [comment]
Getting the same error using 1.9.1  GG changed the name of the character that the reading data error occurs on.

**Comment by CosmicLight** [comment]
ok..after 5 attempts to get the spellings right it worked..haha.

Thank you for the help.

**Comment by Adylucas** [comment]
Thank you

**Comment by Stickymaddness** [comment]
Procurement 1.9.1 has been released, which fixes this issue!

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.1
