### ISSUE TITLE
Error reading character data

### ISSUE THREAD

**Issue by Apeemperor** [Stickymaddness/Procurement#93]
Procurement loads all my standard stash tabs buf fails to load the characters.

Loading characters...                                                                            [OK]
Loading Standard Stash Tab 1...                                                           [OK]
Loading Standard Stash Tab 2...                                                           [OK]
Loading Standard Stash Tab 3...                                                           [OK]
Loading Standard Stash Tab 4...                                                           [OK]
Loading Standard Stash Tab 5...                                                           [OK]
Loading Standard Stash Tab 6...                                                           [OK]
Loading Standard Stash Tab 7...                                                           [OK]
Loading Standard Stash Tab 8...                                                           [OK]
Loading Standard Stash Tab 9...                                                           [OK]
Loading Standard Stash Tab 10...                                                          [OK]
Loading Standard Stash Tab 11...                                                          [OK]
Loading Standard Stash Tab 12...                                                          [OK]
Loading Standard Stash Tab 13...                                                          [OK]
Loading Standard Stash Tab 14...                                                          [OK]
Loading Standard Stash Tab 15...                                                          [OK]
Loading Standard Stash Tab 16...                                                          [OK]
Loading Standard Stash Tab 17...                                                          [OK]
Loading ArcaneMechanics's inventory...                                                    

[Error] Error reading character data for ArcaneMechanics, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

[22-04-2015 17:32] System.Exception: Error reading character data for ArcaneMechanics, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   bei POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh)
   bei Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()

**Comment by comamitc** [comment]
Fix provided here: https://github.com/medvedttn/Procurement/releases/tag/1.9.1

**Comment by blooski** [comment]
Yeah, I am getting the same error.  Tried 2 different accounts.  Something has changed recently.

**Comment by IceLancerSR** [comment]
GGG Server request limit hit, throttling activated. Please wait 38 seconds

**Comment by blooski** [comment]
This is still happening a day later.  The error doesn't seem to go away 
after waiting a few minutes.

**Comment by IceLancerSR** [comment]
It continue it self after 40 seconds or so.I just turned off leagues which do not belong to standard and it doesn't produce wait time any more.

**Comment by blooski** [comment]
I am not sure what you are saying is continuing itself.  I try to log in 
and it gets thru the tabs then on first character I get:

Loading 
characters...                                                                     [OK]
Loading FireDropper's inventory...

[Error] Error reading character data for FireDropper, if you are in 
offline mode you will need to login and update. If you received this 
error while logging in, the authenticated session may have expired or 
bad data has been returned by GGG or a network issue may have occurred - 
Please try again.

Nothing happens after 40 seconds, or if I wait and try again after a 
minute or 2 the same thing happens.

Larry

**Comment by IceLancerSR** [comment]
Fix provided here: https://github.com/medvedttn/Procurement/releases/tag/1.9.1

Use this build it works fine.

**Comment by blooski** [comment]
OK, going to the lastest release seems to have solved the problem.  
Thanks a lot.

Larry

**Comment by Stickymaddness** [comment]
Procurement 1.9.1 has been released, which fixes this issue!

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.1

**Comment by blooski** [comment]
Going to 1.9.1 seemed to have fixed the problem, in my one account at 
least.  However, I tried logging in to a different account today, and 
got this error:

[26-04-2015 22:04] System.Runtime.Serialization.SerializationException: 
Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''.
    at 
System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator 
xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
    at 
System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator 
xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, 
ExtensionDataObject extensionData)
    at ReadRootObjectFromJson(XmlReaderDelegator , 
XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , 
XmlDictionaryString[] )
    at 
System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator 
jsonReader, XmlObjectSerializerReadContextComplexJson context)
    at 
System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator 
jsonReader, XmlObjectSerializerReadContextComplexJson context)
    at 
System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator 
reader, String name, String ns, Type declaredType, DataContract& 
dataContract)
    at 
System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator 
xmlReader, Type declaredType, DataContract dataContract, String name, 
String ns)
    at 
System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator 
xmlReader, Boolean verifyObjectName)
    at 
System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator 
reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
    at 
System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader 
reader)
    at POEApi.Model.POEModel.GetStash(Int32 index, String league, 
Boolean forceRefresh, String accname)
[26-04-2015 22:04] JSON Serialization Failed: base64 bytes:
[26-04-2015 22:04] ZmFsc2U=
[26-04-2015 22:04] END
[26-04-2015 22:04] Error downloading stash for Standard, exception 
details: System.Exception: Downloading stash, details logged to 
DebugInfo.log, please open a ticket at 
https://github.com/Stickymaddness/Procurement/issues
    at POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
    at POEApi.Model.POEModel.GetStash(Int32 index, String league, 
Boolean forceRefresh, String accname)
    at POEApi.Model.POEModel.GetStash(String league, String accname)
[26-04-2015 22:04] System.Exception: Downloading stash for Standard, 
details logged to DebugInfo.log, please open a ticket at 
https://github.com/Stickymaddness/Procurement/issues
    at POEApi.Model.POEModel.GetStash(String league, String accname)
    at 
Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character 
character)
    at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    at 
Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
    at System.Threading.Tasks.Task.Execute()

I upgraded to 1.9.2 and tried again and then got the original error I 
was getting a few days ago, as shown below.

I hope this data is helpful.

Larry
__________________________________________________________________________________________________________________
Loading 
characters...                                                                     [OK]
Loading FireDropper's inventory...

[Error] Error reading character data for FireDropper, if you are in 
offline mode you will need to login and update. If you received this 
error while logging in, the authenticated session may have expired or 
bad data has been returned by GGG or a network issue may have occurred - 
Please try again.

Nothing happens after 40 seconds, or if I wait and try again after a 
minute or 2 the same thing happens.

Larry

**Comment by blooski** [comment]
I went back to 1.9.1 and after playing around some, I discovered that 
long error I listed for problem with loading stash was apparently 
because when I switched accounts I didn't change the account name.
____________________________________________________________________________________________________________
Going to 1.9.1 seemed to have fixed the problem, in my one account at 
least.  However, I tried logging in to a different account today, and 
got this error:

[26-04-2015 22:04] System.Runtime.Serialization.SerializationException: 
Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''.
    at 
System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator 
xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
    at 
System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator 
xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, 
ExtensionDataObject extensionData)
    at ReadRootObjectFromJson(XmlReaderDelegator , 
XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , 
XmlDictionaryString[] )
    at 
System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator 
jsonReader, XmlObjectSerializerReadContextComplexJson context)
    at 
System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator 
jsonReader, XmlObjectSerializerReadContextComplexJson context)
    at 
System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator 
reader, String name, String ns, Type declaredType, DataContract& 
dataContract)
    at 
System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator 
xmlReader, Type declaredType, DataContract dataContract, String name, 
String ns)
    at 
System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator 
xmlReader, Boolean verifyObjectName)
    at 
System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator 
reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
    at 
System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader 
reader)
    at POEApi.Model.POEModel.GetStash(Int32 index, String league, 
Boolean forceRefresh, String accname)
[26-04-2015 22:04] JSON Serialization Failed: base64 bytes:
[26-04-2015 22:04] ZmFsc2U=
[26-04-2015 22:04] END
[26-04-2015 22:04] Error downloading stash for Standard, exception 
details: System.Exception: Downloading stash, details logged to 
DebugInfo.log, please open a ticket at 
https://github.com/Stickymaddness/Procurement/issues
    at POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
    at POEApi.Model.POEModel.GetStash(Int32 index, String league, 
Boolean forceRefresh, String accname)
    at POEApi.Model.POEModel.GetStash(String league, String accname)
[26-04-2015 22:04] System.Exception: Downloading stash for Standard, 
details logged to DebugInfo.log, please open a ticket at 
https://github.com/Stickymaddness/Procurement/issues
    at POEApi.Model.POEModel.GetStash(String league, String accname)
    at 
Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character 
character)
    at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    at 
Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
    at System.Threading.Tasks.Task.Execute()

I upgraded to 1.9.2 and tried again and then got the original error I 
was getting a few days ago, as shown below.

I hope this data is helpful.

Larry
__________________________________________________________________________________________________________________
Loading 
characters...                                                                     [OK]
Loading FireDropper's inventory...

[Error] Error reading character data for FireDropper, if you are in 
offline mode you will need to login and update. If you received this 
error while logging in, the authenticated session may have expired or 
bad data has been returned by GGG or a network issue may have occurred - 
Please try again.

Nothing happens after 40 seconds, or if I wait and try again after a 
minute or 2 the same thing happens.

Larry
